--Test data for database
--Products
INSERT INTO PRODUCT VALUES(1,'Product 1', 31.2);
INSERT INTO PRODUCT VALUES(2,'Product 2', 32.2);
INSERT INTO PRODUCT VALUES(3,'Product 3', 33.2);
INSERT INTO PRODUCT VALUES(4,'Product 4', 34.2);
INSERT INTO PRODUCT VALUES(5,'Product 5', 35.2);
INSERT INTO PRODUCT VALUES(6,'Product 6', 36.2);
INSERT INTO PRODUCT VALUES(7,'Product 7', 37.2);
INSERT INTO PRODUCT VALUES(8,'Product 8', 38.2);
INSERT INTO PRODUCT VALUES(9,'Product 9', 39.2);
INSERT INTO PRODUCT VALUES(10,'Product 10', 41.2);
INSERT INTO PRODUCT VALUES(11,'Product 11', 42.2);
INSERT INTO PRODUCT VALUES(12,'Product 12', 43.2);
--Categories
INSERT INTO CATEGORY VALUES(1,'Categoey 1', 'Desc 1');
INSERT INTO CATEGORY VALUES(2,'Categoey 2', 'Desc 2');
INSERT INTO CATEGORY VALUES(3,'Categoey 3', 'Desc 3');
INSERT INTO CATEGORY VALUES(4,'Categoey 4', 'Desc 4');
INSERT INTO CATEGORY VALUES(5,'Categoey 5', 'Desc 5');
INSERT INTO CATEGORY VALUES(6,'Categoey 6', 'Desc 6');
--Product and Category mappings
INSERT INTO PRODUCT_CATEGORY VALUES(1,1);
INSERT INTO PRODUCT_CATEGORY VALUES(1,3);
INSERT INTO PRODUCT_CATEGORY VALUES(1,6);
INSERT INTO PRODUCT_CATEGORY VALUES(2,1);
INSERT INTO PRODUCT_CATEGORY VALUES(3,2);
INSERT INTO PRODUCT_CATEGORY VALUES(4,2);
INSERT INTO PRODUCT_CATEGORY VALUES(5,3);
INSERT INTO PRODUCT_CATEGORY VALUES(6,3);
INSERT INTO PRODUCT_CATEGORY VALUES(7,4);
INSERT INTO PRODUCT_CATEGORY VALUES(8,4);
INSERT INTO PRODUCT_CATEGORY VALUES(9,5);
INSERT INTO PRODUCT_CATEGORY VALUES(9,6)
INSERT INTO PRODUCT_CATEGORY VALUES(10,5);
INSERT INTO PRODUCT_CATEGORY VALUES(11,6);
INSERT INTO PRODUCT_CATEGORY VALUES(12,6);



